# llmbeans/recommenders/script_gen.py
"""Generate launch scripts from recommendations."""

import os
import stat
from datetime import date


def write_scripts(recommendation, model, output_dir="llmbeans-output"):
    """Write launch scripts and summary to disk.

    Returns a dict mapping file type to absolute path.
    """
    os.makedirs(output_dir, exist_ok=True)
    written = {}

    # Shell script (macOS/Linux)
    shell_path = os.path.join(output_dir, "run.sh")
    with open(shell_path, "w") as f:
        f.write("#!/bin/bash\n")
        f.write(f"# Generated by llmbeans on {date.today().isoformat()}\n")
        f.write(f"# Model: {getattr(model, 'name', 'unknown')}\n")
        f.write(f"# Tool: {getattr(recommendation, 'hosting_tool', 'unknown')}\n")
        f.write("\n")
        command = getattr(recommendation, 'command', '')
        if command:
            f.write(f"{command}\n")
    os.chmod(shell_path, stat.S_IRWXU | stat.S_IRGRP | stat.S_IXGRP | stat.S_IROTH | stat.S_IXOTH)
    written["shell"] = os.path.abspath(shell_path)

    # Batch script (Windows)
    batch_path = os.path.join(output_dir, "run.bat")
    with open(batch_path, "w") as f:
        f.write("@echo off\n")
        f.write(f"REM Generated by llmbeans on {date.today().isoformat()}\n")
        f.write(f"REM Model: {getattr(model, 'name', 'unknown')}\n")
        f.write(f"REM Tool: {getattr(recommendation, 'hosting_tool', 'unknown')}\n")
        f.write("\n")
        command = getattr(recommendation, 'command', '')
        if command:
            f.write(f"{command}\n")
    written["batch"] = os.path.abspath(batch_path)

    # Summary file
    summary_path = os.path.join(output_dir, "summary.txt")
    with open(summary_path, "w") as f:
        f.write(f"llmbeans recommendation\n")
        f.write(f"Generated: {date.today().isoformat()}\n")
        f.write(f"Model: {getattr(model, 'name', 'unknown')}\n")
        f.write(f"Tool: {getattr(recommendation, 'hosting_tool', 'unknown')}\n")
        f.write(f"\n")
        command = getattr(recommendation, 'command', '')
        if command:
            f.write(f"Command:\n{command}\n")
    written["summary"] = os.path.abspath(summary_path)

    return written
