# llmbeans/output/script_gen.py
"""Generate startup scripts from Recommendation objects.

Outputs:
- Shell script (.sh) for macOS/Linux
- Batch file (.bat) for Windows
- Plain text summary
"""

from datetime import datetime

from llmbeans.recommenders.engine import Recommendation
from llmbeans.models.scanner import ModelInfo
from llmbeans.hardware.profiles import HardwareProfileEntry


def generate_summary(
    model: ModelInfo,
    hardware: HardwareProfileEntry,
    rec: Recommendation,
) -> str:
    """Generate a human-readable text summary."""
    lines = [
        "=" * 60,
        f"  llmbeans — {rec.hosting_tool} Configuration",
        "=" * 60,
        "",
        f"  Model:        {model.name}",
        f"  Architecture: {model.architecture}",
        f"  Parameters:   {model.parameter_count}B",
        f"  Quant:        {model.quant_method or 'N/A'} ({model.quant_bits or '?'}-bit)",
        f"  Source:       {'Remote (HF)' if model.is_remote else model.source_path}",
        "",
        f"  Hardware:     {hardware.name}",
        f"  RAM:          {hardware.ram_gb} GB ({hardware.ram_type})",
        f"  GPU:          {hardware.gpu_name}",
    ]

    if hardware.gpu_vram_gb:
        lines.append(f"  GPU VRAM:     {hardware.gpu_vram_gb} GB")
    if hardware.unified_memory:
        lines.append(f"  Unified Mem:  Yes (GPU shares system RAM)")

    lines.extend([
        f"  Bandwidth:    {hardware.memory_bandwidth_gbps} GB/s",
        "",
        "── Performance Estimate ──────────────────────────",
        f"  Est. Speed:   ~{rec.estimated_tok_per_sec} tokens/sec",
        f"  Context:      {rec.context_length} tokens",
        f"  GPU Layers:   {rec.gpu_offload_layers}/{model.num_layers}",
        f"  Threads:      {rec.thread_count}",
        f"  Batch Size:   {rec.batch_size}",
        "",
        "── Memory Estimate ───────────────────────────────",
        f"  Weights:      {rec.memory_breakdown['weights_gb']:.1f} GB",
        f"  KV Cache:     {rec.memory_breakdown['kv_cache_gb']:.1f} GB",
        f"  Overhead:     {rec.memory_breakdown['overhead_gb']:.1f} GB",
        f"  Total:        {rec.memory_breakdown['total_gb']:.1f} GB",
    ])

    if rec.estimated_vram_usage_gb > 0:
        lines.append(f"  GPU Memory:   ~{rec.estimated_vram_usage_gb:.1f} GB")
    if rec.estimated_ram_usage_gb > 0:
        lines.append(f"  System RAM:   ~{rec.estimated_ram_usage_gb:.1f} GB")

    if rec.warnings:
        lines.extend([
            "",
            "── Warnings ──────────────────────────────────────",
        ])
        for w in rec.warnings:
            lines.append(f"  ⚠ {w}")

    lines.extend([
        "",
        "── Command ───────────────────────────────────────",
    ])

    if rec.command:
        for cmd_line in rec.command.split("\n"):
            lines.append(f"  {cmd_line}")

    if rec.extra_config:
        lines.extend([
            "",
            "── Extra Configuration ───────────────────────────",
        ])
        for cfg_line in rec.extra_config.split("\n"):
            lines.append(f"  {cfg_line}")

    lines.extend([
        "",
        f"  Generated by llmbeans on {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        "=" * 60,
    ])

    return "\n".join(lines)


def generate_shell_script(
    model: ModelInfo,
    hardware: HardwareProfileEntry,
    rec: Recommendation,
) -> str:
    """Generate a bash startup script."""
    lines = [
        "#!/usr/bin/env bash",
        f"# llmbeans generated startup script for {model.name}",
        f"# Hosting tool: {rec.hosting_tool}",
        f"# Hardware: {hardware.name}",
        f"# Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        f"# Estimated speed: ~{rec.estimated_tok_per_sec} tok/s",
        "",
        "set -euo pipefail",
        "",
    ]

    # Environment variables
    for key, val in rec.flags.items():
        if key.startswith("OLLAMA_") or key.startswith("CUDA_") or key.startswith("GGML_"):
            lines.append(f'export {key}="{val}"')

    if any(k.startswith("OLLAMA_") or k.startswith("CUDA_") for k in rec.flags):
        lines.append("")

    # Main command
    if rec.command:
        for cmd_line in rec.command.split("\n"):
            lines.append(cmd_line)

    lines.append("")

    return "\n".join(lines)


def generate_batch_script(
    model: ModelInfo,
    hardware: HardwareProfileEntry,
    rec: Recommendation,
) -> str:
    """Generate a Windows batch startup script."""
    lines = [
        "@echo off",
        f"REM llmbeans generated startup script for {model.name}",
        f"REM Hosting tool: {rec.hosting_tool}",
        f"REM Hardware: {hardware.name}",
        f"REM Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        f"REM Estimated speed: ~{rec.estimated_tok_per_sec} tok/s",
        "",
    ]

    for key, val in rec.flags.items():
        if key.startswith("CUDA_") or key.startswith("OLLAMA_") or key.startswith("GGML_"):
            lines.append(f'set "{key}={val}"')

    if any(k.startswith("CUDA_") or k.startswith("OLLAMA_") for k in rec.flags):
        lines.append("")

    if rec.command:
        for cmd_line in rec.command.split("\n"):
            lines.append(cmd_line)

    lines.append("")
    lines.append("pause")

    return "\n".join(lines)


def write_scripts(
    model: ModelInfo,
    hardware: HardwareProfileEntry,
    rec: Recommendation,
    output_dir: str = ".",
    prefix: str = "llmbeans",
) -> dict[str, str]:
    """Write all output files and return {filename: path}."""
    import os
    os.makedirs(output_dir, exist_ok=True)

    files = {}

    # Summary
    summary = generate_summary(model, hardware, rec)
    summary_path = os.path.join(output_dir, f"{prefix}-summary.txt")
    with open(summary_path, "w") as f:
        f.write(summary)
    files["summary"] = summary_path

    # Shell script
    shell = generate_shell_script(model, hardware, rec)
    shell_path = os.path.join(output_dir, f"{prefix}-start.sh")
    with open(shell_path, "w") as f:
        f.write(shell)
    os.chmod(shell_path, 0o755)
    files["shell"] = shell_path

    # Batch script
    batch = generate_batch_script(model, hardware, rec)
    batch_path = os.path.join(output_dir, f"{prefix}-start.bat")
    with open(batch_path, "w") as f:
        f.write(batch)
    files["batch"] = batch_path

    # Extra config (e.g., Modelfile)
    if rec.extra_config:
        config_path = os.path.join(output_dir, f"{prefix}-config")
        with open(config_path, "w") as f:
            f.write(rec.extra_config)
        files["config"] = config_path

    return files
